-- AlterTable
ALTER TABLE "Bookings" ALTER COLUMN "bookingDate" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Passengers" ALTER COLUMN "birthDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "identityExpired" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Payments" ALTER COLUMN "expiredDate" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Promotions" ALTER COLUMN "startDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMPTZ(3);
