runtime: nodejs22

instance_class: F2

health_check:
  enable_health_check: true
  initial_delay_seconds: 300
  check_interval_seconds: 10
  timeout_seconds: 10
  unhealthy_threshold: 3
  healthy_threshold: 2

handlers:
  - url: /.*  
    script: auto
