runtime: nodejs22

instance_class: F2

health_check:
  enable_health_check: true
  check_interval_seconds: 10
  timeout_seconds: 4
  healthy_threshold: 2
  unhealthy_threshold: 3

handlers:
  - url: /.*  
    script: auto
